{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Syntax Errors\n",
    "A syntax error occurs in Python when the interpreter is unable to parse the code due to the code violating Python language rules, such as inappropriate indentation, erroneous keyword usage, or incorrect operator use. Syntax errors prohibit the code from running, and the interpreter displays an error message that specifies the problem and where it occurred in the code. Here's an example of a Python syntax error:\n",
    "\n",
    "x = 2\n",
    "\n",
    "\n",
    "if x == 2\n",
    "\n",
    "print(\"x is 2\")\n",
    "\n",
    "on console:\n",
    "\n",
    "SyntaxError: expected ':'\n",
    "\n",
    "Here above we intentionally made a mistake of inappropriate indentation in if-block and forget to put collon after if-statement.\n",
    "\n",
    "### 2. Runtime Errors\n",
    "In Python, a runtime error occurs when the program is executing and encounters an unexpected condition that prevents it from continuing. Runtime errors are also known as exceptions and can occur for various reasons such as division by zero, attempting to access an index that is out of range, or calling a function that does not exist.\n",
    " ### Types of run-time Errors :-\n",
    "### A. NameError:\n",
    "A NameError in Python is raised when the interpreter encounters a variable or function name that it cannot find in the current scope. This can happen for a variety of reasons, such as misspelling a variable or function name, using a variable or function before it is defined, or referencing a variable or function that is outside the current scope. Here's an example of a NameError in Python:\n",
    "\n",
    "def calculate_sum(a, b):\n",
    "\n",
    "    total = a + b\n",
    "\n",
    "    return total\n",
    "\n",
    "x = 5\n",
    "\n",
    "y = 10\n",
    "\n",
    "z = calculate_sum(x, w)\n",
    "\n",
    "print(z)\n",
    "\n",
    "\n",
    "on console:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "    File \"c:\\Users\\name\\OneDrive\\Desktop\\demo.py\", line 7, in <module>\n",
    "        Z = calculate_sum(x, w)\n",
    "                             ^\n",
    "                             \n",
    "NameError: name 'w' is not defined\n",
    "\n",
    "\n",
    "### B. TypeError:\n",
    "In Python, a TypeError is raised when an operation or function is applied to an object of an inappropriate type. This can happen when trying to perform arithmetic or logical operations on incompatible data types or when passing arguments of the wrong type to a function. Here's an example of a TypeError in Python:\n",
    "\n",
    "\n",
    "x = \"10\"\n",
    "\n",
    "y = 5\n",
    "\n",
    "Z = x + y\n",
    "\n",
    "print(z)\n",
    "\n",
    "on-console:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "\n",
    "      File \"c:\\Users\\name\\OneDrive\\Desktop\\demo.py\", line 3, in <module>\n",
    "        Z = x + y\n",
    "            ~~^~~\n",
    "\n",
    "TypeError: can only concatenate str (not \"int\") to str\n",
    "\n",
    "\n",
    "### B.1 Value error:\n",
    "this kind of errors occured during run-time when user intentionally or unintentionally or for testing program with cutting edge test-cases and values he/she enters the value of var which is not suitable for a d-type of var there.\n",
    "Ex:\n",
    "\n",
    "x=int(input(\"give me the value of x: \"))\n",
    "\n",
    "and if i enter like this :\n",
    "\n",
    "give me the value of x: b\n",
    "\n",
    "then on-console:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "\n",
    "ValueError: invalid literal for int() with base 10: 'b'\n",
    "\n",
    "\n",
    "### C. IndexError\n",
    "An IndexError is raised in Python when we try to access an index of a sequence (such as a string, list, or tuple) that is out of range. This can happen when we try to access an element that doesn't exist in the sequence or when we try to access an element at an index that is greater than or equal to the length of the sequence. Here's an example of an IndexError in Python:\n",
    "\n",
    "my_list = [100, 200, 300, 400, 500]\n",
    "\n",
    "print(my_list[5])\n",
    "\n",
    "on-console:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "\n",
    "      File \"c:\\Users\\name\\OneDrive\\Desktop\\demo.py\", line 2, in <module>\n",
    "        print(my_list[p\n",
    "            ~~^~~\n",
    "\n",
    "IndexError: list index out of range\n",
    "\n",
    "### D. AttributeError\n",
    "In Python, an AttributeErroris raised when you try to access an attribute or method of an object that does not exist or is not defined for that object. This can happen when you misspell the name of an attribute or method or when you try to access an attribute or method that is not defined for the type of object you are working with. Here's an example of an AttributeError in Python:\n",
    "\n",
    "my_string = \"Hello, world!\"\n",
    "\n",
    "my_string.reverse()\n",
    "\n",
    "on-console:\n",
    "\n",
    "  Traceback (most recent call last):\n",
    "    File \"c:\\Users\\name\\OneDrive\\Desktop\\demo.py\", line 2, in <module>\n",
    "        my_string.reverse()\n",
    "        ^^^^^^^^^^^^^^^^^\n",
    "\n",
    "AttributeError: 'str' object has no attribute 'reverse'\n",
    "\n",
    "### 3. Logical Errors\n",
    "A logical error occurs in Python when the code runs without any syntax or runtime errors but produces incorrect results due to flawed logic in the code. These types of errors are often caused by incorrect assumptions, an incomplete understanding of the problem, or the incorrect use of algorithms or formulas.\n",
    "\n",
    "Unlike syntax or runtime errors, logical errors can be challenging to detect and fix because the code runs without producing any error messages. The results may seem correct, but the code might produce incorrect output in certain situations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "cs50pyenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
